default: &default
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  sslmode: require